nomui/nomui

components/Component/Component.js
components/Field/Field.js
components/Field/FieldContent.js
components/Field/demos/get-field.js
components/Field/demos/group.js
components/Field/demos/index.js
components/Field/index.md
components/Field/styles/index.less
components/Form/Form.js
components/Form/demos/complex-control.js
docs/DemoPanel.js
libs/docs-md.css

主要改动，Field 增加了类型，分为单组件，字段组，字段组列表，矩阵，当前只实现了前两种，后两种后续再实现。

Refact field

---

components/Field/Field.js
components/Group/demos/validate.js

fix(Field):  RadioList等组件，在group valid时的tip文案不展示

---

components/Cascader/Cascader.js

closing #444 issue.修复Cascader组件清除按钮无效的bug

fix: 修复Cascader组件清除按钮无效的bug

---

components/Select/Select.js
components/Select/styles/index.less

feat(Select): 多选时支持点击 icon删除已选中的选项，无需打开列表

---

components/Breadcrumb/breadcrumb.js
components/Breadcrumb/styles/index.less
components/Cascader/demos/data.js
components/Cascader/styles/index.less

fix: 修复Breadcrumb面包屑样式bug

---

components/Cascader/demos/data.js
components/Cascader/demos/value.js

fix: 修复Cascader示例的小bug

---

components/Uploader/Uploader.js
components/Uploader/demos/index.js
components/Uploader/demos/validate.js

fix(Uploader): 修复Uploader表单验证

---

components/Uploader/Uploader.js

fix(Uploader): 修复Uploader组件编译报错的bug

fix(Uploader): 修复Uploader组件编译报错的bug

---

components/Tree/TreeNode.js
components/Tree/demos/checkable.js

fix(Tree): 多选 cascadeCheckChildren 和 cascadeCheckParent冲突的问题

---

components/Grid/Grid.js
components/Grid/index.md
components/Table/Td.js

fix(Grid-autoWidth): 自动计算列宽的padding部分

---

components/Grid/GridHeader.js
components/Grid/demos/highlight-col.js
components/Grid/demos/index.js
components/Grid/index.md
components/Grid/styles/index.less
components/Table/Table.js
components/Table/Th.js
components/Table/styles/index.less

feat(Grid): 悬浮表头，对应列高亮

---

components/Cascader/Cascader.js
components/Cascader/demos/data.js
components/NumberSpinner/NumberSpinner.js
components/NumberSpinner/styles/index.less

fix: NumberSpinner数字微调器:修复数字微调器禁用后还能点击操作的bug

fix: NumberSpinner数字微调器:修复数字微调器禁用后还能点击操作的bug

---

components/Field/index.md
components/Group/demos/validate.js
components/util/rule-manager.js

Field新增校验规则，禁止输入<script>危险标签

---

components/Password/Password.js

优化password不能输入*的情况

---

components/Password/Password.js

通过代码setValue而非手动输入时，取值不会更新，重写了setValue方法

fix: Password SetValue方法重写

---

components/GroupGrid/GroupGrid.js

fix: 修改groupGrid组件没有默认值报错问题

---

components/Cascader/Cascader.js
components/Cascader/styles/index.less

修改disable()不能禁用效果
修改disabled属性不能禁用效果

fix: 修改Cascader组件disabled方法和属性无效

---

components/Image/Image.js

style: 残缺图给一个字体最小值

---

components/Tree/Tree.js
components/Tree/index.md

feat: 优化Tree，提供setCheckedNodeKeys（）函数支持设置组件当前选中值

---

components/DatePicker/DatePicker.js
components/DatePicker/TimePickerPanel.js

DatePicker组件Safari对于new  Date()方法的时间格式不兼容

fix: DatePicker组件Safari兼容性bug修复

---

components/Uploader/Uploader.js
components/Uploader/demos/avatar.js
components/Uploader/demos/index.js
components/Uploader/index.md
components/Uploader/styles/index.less

1.用Avatar作为Uploader触发按钮
2.上传完成的列表支持自定义渲染，将上传图片作为替换

feat: Uploader支持自定义t头像上传按钮

---

components/Uploader/Uploader.js
components/Uploader/demos/avatar.js
components/Uploader/styles/index.less

1、删除了自定义红叉按钮，改为用tooltip提示再次上传覆盖
2、组件样式使用错误
3、onRemove调用2次问题修改

fix: Uploader组件自定义上传功能的部分修改

---

components/Cascader/Cascader.js
components/Cascader/CascaderList.js
components/Cascader/demos/disabled.js
components/Cascader/demos/index.js
components/Cascader/index.md
components/Cascader/styles/index.less

feat: Cascader 添加新功能，配置子项的disable属性

---

components/Cascader/Cascader.js
components/Cascader/index.md

fix: Cascader: 添加选取非叶子节点的需求

---

components/TreeSelect/TreeSelectPopup.js
components/TreeSelect/demos/searchable-local.js

Resolves #934 
TODO
TreeSelect搜索到结果时展开节点层级，不搜索时还原组件的initExpandLevel层级设置

TreeSelect组件搜索显示优化

---

components/Menu/MenuItemWrapper.js

fix(Meun): Meun三级导航页面问题

---

components/Tag/Tag.js
components/Tag/demos/basic.js
components/Tag/index.md

docs(Tag):Tag组件删除回调文档修改

---

components/TreeSelect/TreeSelect.js
components/TreeSelect/TreeSelectPopup.js
components/TreeSelect/demos/searchable-local.js

fix(treeSelect): issue982SeleteTree初始化，如果是子节点，数据不会展开"

fix(treeSelect): issue982SeleteTree初始化，如果是子节点，数据不会展开"

---

components/Cascader/Cascader.js
components/Cascader/index.md

feat: Cascader组件allowClear属性要求能够配置

---

components/Select/Select.js

Resolves #944 
**TODO** 
Select无数据时会默认显示‘无数据’

feat: Select支持无数据时默认显示‘无数据’

---

components/Table/Td.js

fix: Grid单独获取某行进行更新会导致固定列失效

---

components/Tree/Tree.js
components/Tree/index.md
components/TreeSelect/TreeSelect.js
components/TreeSelect/demos/multiple.js

fix: 修改TreeSelect组件选中一个后滚动条不要滑动，应保持原位置不变

---

components/TreeSelect/TreeSelect.js

fix: 修改treeSelect组件报错

---

components/Component/Component.js

修改echarts update时nomui报错

---

components/Grid/Grid.js
components/Grid/demos/cascade.js
components/Grid/index.md
components/Grid/styles/index.less
components/Table/Td.js
components/Table/Th.js
components/Table/Tr.js

rowCheckable:{
combined:boolean // 为true的时候勾选框跟随树级
}

feat(Grid): 新增勾选框跟随在树级后面配置

---

components/Table/Td.js
components/util/index.js

- 优化对数组与对象的比较
- 取值如果是数组,两个数组顺序不同但元素内容相同算作未修改

perf(Group): 优化excelMode新旧值比较

---

components/Cascader/Cascader.js
components/Cascader/CascaderList.js
components/Cascader/demos/cascade.js
components/Cascader/demos/index.js
components/Cascader/demos/multiple.js
components/Cascader/demos/remote.js
components/Cascader/demos/value.js
components/Cascader/index.md
components/Cascader/styles/index.less
components/Checkbox/styles/index.less

feat(Cascader): 实现多选以及级联多选

---

components/Grid/Grid.js
components/Grid/demos/cascadeCheckChildren.js
components/Grid/demos/cascadeCheckParent.js
components/Grid/demos/index.js
components/Grid/demos/partial-checked.js
components/Grid/index.md
components/Table/Tr.js

| 名称 | 说明 | 类型 |
| --- | --- | --- |
| getCheckedRows | 获取当前选中行数组，参数 includePartialChecked 表示包括半勾选状态的节点 | `({includePartialChecked:true})=>{}` |
| getCheckedRowKeys | 获取当前选中行的 key 数组，参数 includePartialChecked 表示包括半勾选状态的节点 | `({includePartialChecked:true})=>{}` |
表格行可勾选配置
| 参数 | 说明 | 类型 | 默认值 |
| --- | --- | --- | --- |
| includePartialChecked | 获取勾选行是否包括半勾选状态的 | `boolean` | true |

Grid勾选实现半勾选状态

---

components/Select/SelectPopup.js
components/TreeSelect/TreeSelectPopup.js

背景需求：
配置 Select 组件的 filter 远程搜索的时候需要操作到组件本身

feat: select、treeSelect filter 方法暴露当前组件实例
